# Generated by Django 4.1.6 on 2023-02-07 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(choices=[['Ping', 'Ping'], ['HTTP(S)', 'HTTP(S)'], ['Port', 'Port']], max_length=100)),
                ('friendly_name', models.CharField(max_length=100)),
                ('url_or_ip', models.CharField(max_length=100)),
                ('monitoring_interval', models.IntegerField()),
                ('monitor_timeout', models.IntegerField(default=30)),
                ('monitor_ssl', models.BooleanField(default=False)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ip_up', models.BooleanField(default=False)),
                ('ssl_up', models.BooleanField(default=False)),
                ('date_timer', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor')),
            ],
        ),
    ]
