# Generated by Django 4.1.6 on 2023-02-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ip_up', models.BooleanField(default=False)),
                ('ssl_up', models.BooleanField(default=False)),
                ('date_timer', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor')),
            ],
        ),
    ]
