# Generated by Django 4.1.6 on 2023-02-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitor_port_monitorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='monitor_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[['Ping', 'Ping'], ['HTTP(S)', 'HTTP(S)'], ['Port', 'Port']], max_length=100),
        ),
    ]
